org: romion404
app: serverless-twilio
service: serverless-twilio

plugins:
  - serverless-apigw-binary

provider:
  name: aws
  runtime: nodejs18.x
  memorySize: 128
  timeout: 30
  environment:
    TWILIO_ACCOUNT_SID: YOUR-TWILIO-ACCOUNT-SID-HERE
    TWILIO_AUTH_TOKEN: YOUR-TWILIO-AUTH-TOKEN-HERE
    TWILIO_PHONE_NUMBER: YOUR-TWILIO-PHONE-NUMBER-HERE

package:
  exclude:
    - ./**
  include:
    - "node_modules/**"
    - "frontend/dist/**"
    - "functions/**"

custom:
  apigwBinary:
    types:
      - '*/*'

functions:
  api:
    handler: functions/frontend.runServerless
    events:
      - http: GET {proxy+}
      - http: GET /
  sendText:
    handler: functions/sms.sendText
    events:
      - http:
          path: api/sendText
          method: post
          integration: lambda
          cors: true
